services:

  # PHP service
  app:
    build: .
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # MySQL database service
  db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge